---

# A docker-compose file to simplify image testing.
#
#   NOTE: This file assumes docker-compose v1.27.0 or better.
#
# Use to build and test an image using the following environment variables:
#
# - IMAGE_NAME (default 'formatter')
# - DATASET_NAME (default '1')
# - DATASET_FILE (default 'dummy.txt')
#
# See TESTING.md

services:
  formatter:
    build: .
    image: ${IMAGE_NAME:-formatter}:latest
    environment:
    - DT_DATASET_NAME=${DATASET_NAME:-1}
    - DT_DATASET_FILE=/dataset/input/${DATASET_FILE:-dummy.txt}
    - DT_DATASET_OUTPUT_PATH=/dataset/output
    volumes:
    - ${PWD}/test/success/${DATASET_NAME:-1}:/dataset
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
